{
 "PRed": [
  {
   "data": {
    "bot_rerun": false,
    "migrator_name": "Version",
    "migrator_version": 0,
    "version": "0.4.2"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_version",
    "version"
   ]
  },
  {
   "PR": {
    "number": 2,
    "state": "closed"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "Compiler",
    "migrator_version": 0
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_version"
   ]
  },
  {
   "PR": {
    "number": 3,
    "state": "closed"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "CompilerRebuild",
    "migrator_version": 1,
    "name": "Python 3.7, GCC 7, R 3.5.1, openBLAS 0.3.2"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_version",
    "name"
   ]
  },
  {
   "PR": {
    "number": 5,
    "state": "closed"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "MigrationYaml",
    "migrator_object_version": 1,
    "migrator_version": 0,
    "name": "python38"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_object_version",
    "migrator_version",
    "name"
   ]
  },
  {
   "PR": {
    "number": 6,
    "state": "closed"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "MigrationYaml",
    "migrator_object_version": 1,
    "migrator_version": 0,
    "name": "pypy"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_object_version",
    "migrator_version",
    "name"
   ]
  },
  {
   "PR": {
    "labels": [],
    "number": 7,
    "state": "closed"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "MigrationYaml",
    "migrator_object_version": 2,
    "migrator_version": 0,
    "name": "python39"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_object_version",
    "migrator_version",
    "name"
   ]
  },
  {
   "PR": {
    "labels": [],
    "number": 8,
    "state": "closed"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "Version",
    "migrator_version": 0,
    "version": "0.5.0"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_version",
    "version"
   ]
  },
  {
   "PR": {
    "labels": [],
    "number": 9,
    "state": "closed"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "MigrationYaml",
    "migrator_object_version": 1,
    "migrator_version": 0,
    "name": "python310"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_object_version",
    "migrator_version",
    "name"
   ]
  },
  {
   "PR": {
    "__lazy_json__": "pr_json/1654118363.json"
   },
   "data": {
    "bot_rerun": false,
    "migrator_name": "Version",
    "migrator_version": 0,
    "version": "0.6.0"
   },
   "keys": [
    "bot_rerun",
    "migrator_name",
    "migrator_version",
    "version"
   ]
  }
 ],
 "bad": false,
 "pinning_version": "2023.12.21.09.51.46",
 "pre_pr_migrator_attempts": {
  "pypy38": 363,
  "python311": 838,
  "python312": 143
 },
 "pre_pr_migrator_status": {
  "pypy38": "not solvable (<a href='https://github.com/regro/cf-scripts/actions/runs/7382674276'>bot CI job</a>) @ main\n<details>\n<div align=\"left\">\n<pre>\nNo `.ci_support/*.yaml` files found! This can happen when a rerender results in no builds for a recipe (e.g., a recipe is python 2.7 only). This attempted migration is being reported as not solvable.\n</pre>\n</div>\n</details>",
  "python311": "not solvable (<a href=\"https://github.com/regro/cf-scripts/actions/runs/6245774259\">bot CI job</a>): main: ['No `.ci_support/*.yaml` files found! This can happen when a rerender results in no builds for a recipe (e.g., a recipe is python 2.7 only). This attempted migration is being reported as not solvable.']",
  "python312": "bot error (<a href=\"https://github.com/regro/cf-scripts/actions/runs/7400986297\">bot CI job</a>): main: Traceback (most recent call last):\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py\", line 1270, in _run_migrator\n    migrator_uid, pr_json = run(\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py\", line 394, in run\n    _set_pre_pr_migrator_fields(\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py\", line 146, in _set_pre_pr_migrator_fields\n    with attrs[\"pr_info\"] as pri:\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/lazy_json_backends.py\", line 655, in __exit__\n    self._dump(purge=True)\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/lazy_json_backends.py\", line 625, in _dump\n    backend.hset(self.hashmap, self.node, data_str)\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/lazy_json_backends.py\", line 246, in hset\n    coll.update_one(\n  File \"/home/runner/miniconda3/envs/cf-scripts/lib/python3.10/site-packages/pymongo/collection.py\", line 1086, in update_one\n    self._update_retryable(\n  File \"/home/runner/miniconda3/envs/cf-scripts/lib/python3.10/site-packages/pymongo/collection.py\", line 881, in _update_retryable\n    return self.__database.client._retryable_write(\n  File \"/home/runner/miniconda3/envs/cf-scripts/lib/python3.10/site-packages/pymongo/mongo_client.py\", line 1523, in _retryable_write\n    return self._retry_with_session(retryable, func, s, bulk)\n  File \"/home/runner/miniconda3/envs/cf-scripts/lib/python3.10/site-packages/pymongo/mongo_client.py\", line 1421, in _retry_with_session\n    return self._retry_internal(\n  File \"/home/runner/miniconda3/envs/cf-scripts/lib/python3.10/site-packages/pymongo/_csot.py\", line 107, in csot_wrapper\n    return func(self, *args, **kwargs)\n  File \"/home/runner/miniconda3/envs/cf-scripts/lib/python3.10/site-packages/pymongo/mongo_client.py\", line 1462, in _retry_internal\n    ).run()\n  File \"/home/runner/miniconda3/envs/cf-scripts/lib/python3.10/site-packages/pymongo/mongo_client.py\", line 2315, in run\n    return self._read() if self._is_read else self._write()\n  File \"/home/runner/miniconda3/envs/cf-scripts/lib/python3.10/site-packages/pymongo/mongo_client.py\", line 2412, in _write\n    self._server = self._get_server()\n  File \"/home/runner/miniconda3/envs/cf-scripts/lib/python3.10/site-packages/pymongo/mongo_client.py\", line 2400, in _get_server\n    return self._client._select_server(\n  File \"/home/runner/miniconda3/envs/cf-scripts/lib/python3.10/site-packages/pymongo/mongo_client.py\", line 1303, in _select_server\n    server = topology.select_server(server_selector)\n  File \"/home/runner/miniconda3/envs/cf-scripts/lib/python3.10/site-packages/pymongo/topology.py\", line 302, in select_server\n    server = self._select_server(selector, server_selection_timeout, address)\n  File \"/home/runner/miniconda3/envs/cf-scripts/lib/python3.10/site-packages/pymongo/topology.py\", line 286, in _select_server\n    servers = self.select_servers(selector, server_selection_timeout, address)\n  File \"/home/runner/miniconda3/envs/cf-scripts/lib/python3.10/site-packages/pymongo/topology.py\", line 237, in select_servers\n    server_descriptions = self._select_servers_loop(selector, server_timeout, address)\n  File \"/home/runner/miniconda3/envs/cf-scripts/lib/python3.10/site-packages/pymongo/topology.py\", line 259, in _select_servers_loop\n    raise ServerSelectionTimeoutError(\npymongo.errors.ServerSelectionTimeoutError: No primary available for writes, Timeout: 30s, Topology Description: <TopologyDescription id: 6595a6e37c3dd4576cc4e28e, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-k3atodu-shard-00-00.mvdqvie.mongodb.net', 27017) server_type: RSSecondary, rtt: 0.05318170026196722>, <ServerDescription ('ac-k3atodu-shard-00-01.mvdqvie.mongodb.net', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('SSL handshake failed: ac-k3atodu-shard-00-01.mvdqvie.mongodb.net:27017: _ssl.c:990: The handshake operation timed out (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('ac-k3atodu-shard-00-02.mvdqvie.mongodb.net', 27017) server_type: RSSecondary, rtt: 0.05333186849359896>]>\n"
 },
 "smithy_version": "3.30.2"
}